server:
  port: 9090
spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      #host: mymongodb
      host: localhost
      #port: 27017
      port: 27018
      database: weather-api
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger-ui.html
logging:
  level:
    org.springframework.web: INFO
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
